### ISSUE TITLE
Go: review and refactor Go code.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/terraform-provider-serverless#6]
... let's take just another stab to make sure our Go is idiomatic and the full dev experience works for a go dev.

- [ ] Get the localdev setup going for the go code to check (at least run lint) for everything
- [ ] refactor anything appropriate

**Comment by dmmulroy** [comment]
I have an initial refactor done on the [go-code-review](https://github.com/FormidableLabs/terraform-provider-serverless/tree/go-code-review) branch.  Planning on opening a draft PR tomorrow and organizing my thoughts to get feedback 👍
